### ISSUE TITLE
Missing CLAs

### ISSUE THREAD

**Issue by adewes** [kiebitz-oss/apps#47]
This is an issue where contributors with missing CLAs are tagged. Please sign (or have your organization sign) the appropriate CLA available at https://kiebitz.eu/en/docs/open-source/contribute/overview. Only contributions with a valid CLA can remain in the repository. Thank you.

**Comment by adewes** [comment]
@benbender

**Comment by fschoenfeldt** [comment]
@adewes the links in the https://github.com/kiebitz-oss/apps#participation section don't work, so they're literally missing, just FYI.
